---
extends: default

rules:
  line-length:
    max: 120
    level: warning
  document-start: disable
  comments-indentation: disable
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
    check-keys: false

ignore: |
  .venv/
  venv/
  __pycache__/
  .pytest_cache/
  .mypy_cache/
  data/
  logs/
  reports/
