"""Local filesystem dataset store."""

import contextlib
import errno
import fcntl
import hashlib
import io
import json
import logging
import os
import re
import stat
import uuid
import weakref
from collections.abc import Iterator
from datetime import datetime
from pathlib import Path

# from typing import Any, Dict, List, Optional
from typing import Any

import numpy as np

from juniper_data.core.constants import CHARSET_UTF8
from juniper_data.core.models import DatasetMeta
from juniper_data.storage.base import DatasetStore, InvalidDatasetIdError, StagedSave, StorageContainmentError
from juniper_data.storage.constants import (
    ARTIFACT_STREAM_CHUNK_SIZE,
    DEFAULT_LIST_LIMIT,
    DEFAULT_LIST_OFFSET,
    JSON_INDENT_DEFAULT,
    LOCK_DIR_NAME,
    LOCK_FILE_SUFFIX,
    LOCK_STRIPE_COUNT,
    META_FILE_SUFFIX,
    NPZ_FILE_SUFFIX,
    TMP_FILE_SUFFIX,
)

# Dataset IDs are generated by ``generate_dataset_id`` as
# ``{generator}-{version}-{hash[:16]}`` where version strings may contain
# dots (e.g. ``spiral-v1.0.0-a3f8e12b4c567890``). The allowlist accepts
# alphanumerics, dot, underscore, and hyphen — explicitly excluding path
# separators, ``..`` parent references, and leading dots that could map to
# hidden files outside the storage directory (JD-SEC-01).
_VALID_DATASET_ID = re.compile(r"[A-Za-z0-9][A-Za-z0-9._\-]{0,127}")

logger = logging.getLogger(__name__)

# Keys of the descriptors a store holds open (``LocalFSDatasetStore._descriptors``).
_ROOT = "root"
_LOCKS = "locks"

# Why creating a file or directory can fail when nothing is wrong with the request: no inode or
# block left, no quota, a read-only volume, or no write permission. A lock then falls back to
# the storage root, which needs no new inode (``LocalFSDatasetStore._meta_write_lock``).
_NO_NEW_ENTRY = frozenset({errno.ENOSPC, errno.EDQUOT, errno.EROFS, errno.EACCES, errno.EPERM})


def _stripe_file_name(stripe: int) -> str:
    """The file name of lock stripe ``stripe``: ``0.lock`` to ``f.lock``."""
    return f"{stripe:x}{LOCK_FILE_SUFFIX}"


def _close_descriptors(descriptors: dict[str, int]) -> None:
    """Close the descriptors a store held, when it is collected."""
    for fd in descriptors.values():
        with contextlib.suppress(OSError):
            os.close(fd)
    descriptors.clear()


def _discard_temp(path: Path, what: str) -> None:
    """Remove a temporary file a save left, best effort."""
    try:
        path.unlink(missing_ok=True)
    except OSError:
        logger.debug("Failed to remove temporary %s file %s during cleanup", what, path, exc_info=True)


def _validate_dataset_id(dataset_id: str) -> None:
    """Validate ``dataset_id`` against path traversal attacks.

    Raises:
        InvalidDatasetIdError: If ``dataset_id`` is not a well-formed identifier.
            A ``ValueError``; the caller is expected to translate it into an
            HTTP 400 at the request boundary, which the app's ``ValueError``
            handler does.
    """
    if not isinstance(dataset_id, str) or not dataset_id:
        raise InvalidDatasetIdError("dataset_id must be a non-empty string")
    if ".." in dataset_id:
        raise InvalidDatasetIdError(f"Invalid dataset_id: {dataset_id!r}")
    if not _VALID_DATASET_ID.fullmatch(dataset_id):
        raise InvalidDatasetIdError(f"Invalid dataset_id: {dataset_id!r}")


def _json_serializer(obj: Any) -> str:
    """JSON serializer for objects not serializable by default."""
    if isinstance(obj, datetime):
        return obj.isoformat()
    raise TypeError(f"Object of type {type(obj).__name__} is not JSON serializable")


class LocalFSDatasetStore(DatasetStore):
    """Local filesystem implementation of DatasetStore.

    Stores datasets as JSON metadata files and NPZ array files.

    Storage layout:
        {base_path}/{dataset_id}.meta.json
        {base_path}/{dataset_id}.npz
        {base_path}/locks/{0..f}.lock   -- the cross-process lock stripes, created with the store
    """

    def __init__(self, base_path: Path) -> None:
        """Initialize the local filesystem store.
        Args:
            base_path: Base directory for storing datasets. Created if it doesn't exist.
        """
        # JD-PERF-02. Without this the metadata cache is INERT for this store --
        # ``_list_all_metadata_cached`` degrades to an uncached disk walk when
        # ``_metadata_cache_lock`` is absent, and this is the store the service
        # actually wires (``api/app.py``). Measured cost of the omission: 121.8x
        # at 100 datasets, 141.1x at 1,000.
        super().__init__()
        self._base_path = Path(base_path)
        self._base_path.mkdir(parents=True, exist_ok=True)
        # Cache the resolved base so every lookup does not re-resolve symlinks.
        # The cached value is used as the reference point for the
        # defense-in-depth containment check in ``_build_path`` (JD-SEC-01).
        self._resolved_base = self._base_path.resolve()
        self._lock_dir = self._base_path / LOCK_DIR_NAME
        # Descriptors held for the store's life. The storage root is opened once -- again only if
        # it is removed and made again -- and ``locks/`` once, without following a symlink: a
        # stripe is then opened THROUGH that descriptor, so a ``locks`` swapped for a symlink
        # after startup is never followed. The root is also the lock of last resort, which needs
        # no inode (``_meta_write_lock``). Nothing closes a store, so they are closed when it is
        # collected.
        self._descriptors: dict[str, int] = {}
        weakref.finalize(self, _close_descriptors, self._descriptors)
        self._descriptors[_ROOT] = os.open(self._base_path, os.O_RDONLY | os.O_DIRECTORY | os.O_CLOEXEC)
        if self._open_lock_dir() is not None:
            self._create_lock_stripes()
        self._remove_legacy_lock_files()

    def _open_lock_dir(self) -> int | None:
        """Open ``locks/`` in the storage root, creating it if it is absent, and keep the descriptor.

        When the directory the root descriptor holds is gone -- the storage root was removed, and
        perhaps made again -- the root is opened again first (``_reopen_root``).

        Returns:
            The descriptor, or ``None`` when the directory is absent and cannot be created -- the
            volume is out of inodes, read-only, or not writable. Every lock then falls back to
            the storage root (``_meta_write_lock``), and this is tried again at the next lock.

        Raises:
            StorageContainmentError: what is at ``locks`` is not a real directory: a symlink,
                wherever it points -- inside the root too -- or a file. Nothing is locked through
                it, and a store that finds one when it opens does not open: a service that
                started would answer every write with a 500.
        """
        root = self._descriptors[_ROOT]
        try:
            try:
                os.mkdir(LOCK_DIR_NAME, 0o700, dir_fd=root)
            except FileNotFoundError:
                root = self._reopen_root()
                os.mkdir(LOCK_DIR_NAME, 0o700, dir_fd=root)
        except FileExistsError:
            pass
        except OSError as exc:
            if exc.errno not in _NO_NEW_ENTRY:
                raise
            logger.warning("Could not create the lock directory in %s (%s); every lock falls back to the storage root until it exists", self._base_path, type(exc).__name__)
            return None
        try:
            fd = os.open(LOCK_DIR_NAME, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW | os.O_CLOEXEC, dir_fd=root)
        except OSError as exc:
            if exc.errno in (errno.ELOOP, errno.ENOTDIR):
                raise StorageContainmentError(f"{self._lock_dir} is not a real directory in the storage root; the store will not lock through it") from None
            raise
        self._descriptors[_LOCKS] = fd
        return fd

    def _reopen_root(self) -> int:
        """Open the storage root again, by path, in place of a descriptor whose directory is gone.

        ``mkdir`` through a descriptor fails with ``ENOENT`` only when the directory it holds was
        removed. Every other operation of this store finds the root by path, so the locks follow
        it to a root made again at that path; if there is none, the ``FileNotFoundError`` stands.
        """
        fd = os.open(self._base_path, os.O_RDONLY | os.O_DIRECTORY | os.O_CLOEXEC)
        os.close(self._descriptors[_ROOT])
        self._descriptors[_ROOT] = fd
        return fd

    def _create_lock_stripes(self) -> None:
        """Create every lock stripe now, so that taking a lock never needs a new inode.

        With a lock file per dataset id, created on first use and never removed, each
        request naming an absent id left a file behind, and ``DELETE`` had to create one
        before it could unlink anything -- so on a volume out of inodes the operations that
        free space were the ones that failed. The stripes are a fixed set, created here and
        then only ever opened.

        Each stripe is tried on its own, and one that cannot be created -- a symlink planted at
        it, which ``O_NOFOLLOW`` refuses -- does not stop the others. Best effort: a stripe still
        missing is created when first locked, once the directory is writable; until then, a lock
        on it falls back to the storage root.
        """
        failed: list[str] = []
        for stripe in range(LOCK_STRIPE_COUNT):
            try:
                os.close(os.open(_stripe_file_name(stripe), os.O_CREAT | os.O_RDWR | os.O_NOFOLLOW | os.O_CLOEXEC, 0o600, dir_fd=self._descriptors[_LOCKS]))
            except OSError as exc:
                failed.append(type(exc).__name__)
        if failed:
            logger.warning("Could not create %d of the %d lock stripes in %s (%s)", len(failed), LOCK_STRIPE_COUNT, self._lock_dir, ", ".join(sorted(set(failed))))

    def _remove_legacy_lock_files(self) -> None:
        """Remove the per-dataset lock files an earlier version created in the storage root.

        Before the stripes, LocalFS created ``<dataset_id>.meta.json.lock`` beside the metadata
        on first use and never removed it: one for every id a request had named, present or not.
        They lock nothing now, and on a volume they filled they are the inodes a delete needs.
        Only an entry directly in the root, not a directory, whose name is a valid dataset id
        followed by exactly ``.meta.json.lock`` is removed. An earlier version still running
        against this directory locks those files, so do not run one beside this one.
        """
        suffix = META_FILE_SUFFIX + LOCK_FILE_SUFFIX
        removed = 0
        failed: list[str] = []
        for path in self._base_path.glob("*" + suffix):
            if not _VALID_DATASET_ID.fullmatch(path.name[: -len(suffix)]):
                continue
            try:
                if stat.S_ISDIR(path.lstat().st_mode):
                    continue
                path.unlink()
                removed += 1
            except OSError as exc:
                failed.append(type(exc).__name__)
        if removed:
            logger.info("Removed %d lock files an earlier version left in %s", removed, self._base_path)
        if failed:
            logger.warning("Could not remove %d lock files an earlier version left in %s (%s)", len(failed), self._base_path, ", ".join(sorted(set(failed))))

    def _build_path(self, dataset_id: str, suffix: str) -> Path:
        """Construct a storage path for ``dataset_id`` with traversal defense.

        Applies two layers of protection (JD-SEC-01):

        1. ``_validate_dataset_id`` rejects identifiers containing parent
           references, path separators, or any character outside the
           permitted alphabet before the filesystem is touched.
        2. The constructed path is resolved and required to remain within
           ``self._resolved_base``, catching any traversal that slips past
           the regex via filesystem-level tricks (symlink abuse, etc.).

        Layer 1 refuses the CALLER's id (``InvalidDatasetIdError``). Layer 2 can only fire for
        an id layer 1 accepted -- no separator, no ``..`` -- so what it catches is the storage
        directory's own state, a symlink that leads out of it, and it raises
        ``StorageContainmentError``: a storage fault, not a malformed request.
        """
        _validate_dataset_id(dataset_id)
        candidate = self._base_path / f"{dataset_id}{suffix}"
        resolved = candidate.resolve() if candidate.exists() else (self._resolved_base / candidate.name).resolve()
        if not resolved.is_relative_to(self._resolved_base):
            raise StorageContainmentError(f"Path traversal detected for dataset_id: {dataset_id!r}")
        return candidate

    def _meta_path(self, dataset_id: str) -> Path:
        """Get path to metadata file."""
        return self._build_path(dataset_id, META_FILE_SUFFIX)

    def _stripe_name(self, dataset_id: str) -> str:
        """The name of the lock stripe guarding one dataset's metadata: ``sha256(id)`` mod the stripe count.

        The id is validated first, so a hostile id is refused before any file is touched, as
        by every other path this store builds.
        """
        _validate_dataset_id(dataset_id)
        return _stripe_file_name(int(hashlib.sha256(dataset_id.encode(CHARSET_UTF8)).hexdigest(), 16) % LOCK_STRIPE_COUNT)

    def _lock_path(self, dataset_id: str) -> Path:
        """Where ``dataset_id``'s lock stripe is. For reading only: the store opens it through ``locks/``'s descriptor."""
        return self._lock_dir / self._stripe_name(dataset_id)

    def _open_lock_stripe(self, name: str) -> int | None:
        """Open a lock stripe through the held ``locks/`` descriptor; create it only if it is missing.

        ``O_NOFOLLOW``: a symlink planted at a stripe is refused, never followed out of the
        storage root, and ``locks`` itself is not re-resolved -- the descriptor is. ``O_CLOEXEC``:
        the descriptor does not leak into a child process. The stripe is opened without
        ``O_CREAT`` first, so the normal path creates nothing and needs no free inode.

        Returns:
            The stripe's descriptor, or ``None`` when it is missing and cannot be created (no
            inode, a read-only or unwritable directory): the caller then locks the root.
        """
        flags = os.O_RDWR | os.O_NOFOLLOW | os.O_CLOEXEC
        for _attempt in range(2):
            locks = self._descriptors.get(_LOCKS)
            if locks is None:
                locks = self._open_lock_dir()
                if locks is None:
                    return None
            with contextlib.suppress(FileNotFoundError):
                return os.open(name, flags, dir_fd=locks)
            try:
                # 0o600: the lock file carries no data -- it exists only as an flock target --
                # so nothing needs to read it and a world-readable mode is pure exposure
                # (CodeQL py/overly-permissive-file). Every process locking it runs as the
                # service user; cross-user locking would be a deliberate change, not a default.
                return os.open(name, flags | os.O_CREAT, 0o600, dir_fd=locks)
            except FileNotFoundError:
                # The directory the descriptor holds was removed: open whatever is at
                # ``locks`` now, and try once more.
                os.close(self._descriptors.pop(_LOCKS))
            except OSError as exc:
                if exc.errno in _NO_NEW_ENTRY:
                    return None
                raise
        return None

    @contextlib.contextmanager
    def _meta_write_lock(self, dataset_id: str) -> Iterator[None]:
        """Hold an exclusive advisory lock on this dataset's metadata (APD-DATA-007).

        The base class serialises the metadata read-modify-write only within one
        interpreter. Because this store's state is a shared directory, two *processes*
        against the same ``storage_path`` interleave freely, and the loser's whole
        document is overwritten. Reproduced before the fix: twelve processes each adding
        one distinct tag left two tags on disk.

        A separate lock file is used rather than locking the metadata file itself: the
        write path replaces that file by ``rename``, so a lock held on the old inode
        would guard nothing once the first writer swapped it out. The lock files are a
        fixed set of stripes (``_create_lock_stripes``), never renamed or removed --
        unlinking one would let a second process create and lock a *different* inode by
        the same name and immediately enter the critical section.

        Two datasets on one stripe share its lock. Within a process that costs nothing,
        because ``_version_lock`` already serialises every metadata write. Across processes
        it does: a lock another process holds on any dataset of the stripe -- one in sixteen
        -- delays this process's lock takers on every dataset of that stripe, for as long as
        the other process holds it.

        When the stripe is missing and cannot be created -- the volume is out of inodes, or
        the directory is not writable -- the lock is taken on the storage root itself,
        exclusively, which needs no inode. Every stripe lock also holds the root SHARED, so a
        root lock taken by any process excludes every stripe lock, and stripes still exclude
        only each other. Callers hold ``_version_lock`` first, so no two threads of a process
        are ever in here at once -- and the root's lock relies on that: a ``flock`` belongs to
        the open descriptor, which every lock this store takes shares, so one thread's unlock
        would release another's.

        ``flock`` is advisory and per-host. It orders writers on one machine, including
        separate uvicorn workers, but is not a distributed lock and gives no guarantee
        over NFS.
        """
        name = self._stripe_name(dataset_id)
        stripe = self._open_lock_stripe(name)
        # Read only now: opening the stripe can replace the root's descriptor (``_reopen_root``).
        root = self._descriptors[_ROOT]
        try:
            fcntl.flock(root, fcntl.LOCK_EX if stripe is None else fcntl.LOCK_SH)
            try:
                if stripe is not None:
                    fcntl.flock(stripe, fcntl.LOCK_EX)
                try:
                    yield
                finally:
                    if stripe is not None:
                        fcntl.flock(stripe, fcntl.LOCK_UN)
            finally:
                fcntl.flock(root, fcntl.LOCK_UN)
        finally:
            if stripe is not None:
                os.close(stripe)

    def _tmp_path(self, final_path: Path) -> Path:
        """A temp path unique to this process and call.

        BUG-JD-03 writes to a sibling temp file and ``replace()``s it over the final
        path so a crash cannot leave partial JSON readable. That temp name used to be
        derived from the final path alone, so two processes writing the same dataset
        chose the *same* temp file: one would replace it away while the other was still
        using it, and the loser raised ``FileNotFoundError`` mid-write. Found while
        reproducing APD-DATA-007. The pid+uuid suffix makes collision impossible; the
        atomic ``replace`` onto the final path is unchanged.
        """
        return final_path.with_suffix(f"{final_path.suffix}.{os.getpid()}.{uuid.uuid4().hex[:8]}{TMP_FILE_SUFFIX}")

    def _npz_path(self, dataset_id: str) -> Path:
        """Get path to NPZ file."""
        return self._build_path(dataset_id, NPZ_FILE_SUFFIX)

    def save(
        self,
        dataset_id: str,
        meta: DatasetMeta,
        arrays: dict[str, np.ndarray],
    ) -> None:
        """Save dataset metadata and arrays to filesystem.

        The two halves :meth:`save_versioned` runs apart -- :meth:`stage_save` outside the
        locks, its commit under them -- run here back to back. This takes no lock itself.

        Args:
            dataset_id: Unique identifier for the dataset.
            meta: Dataset metadata.
            arrays: Dictionary of numpy arrays.

        Raises:
            IOError: If the save operation fails.
        """
        staged = self.stage_save(dataset_id, arrays)
        try:
            staged.commit(meta)
        finally:
            staged.discard()

    def stage_save(self, dataset_id: str, arrays: dict[str, np.ndarray]) -> StagedSave:
        """Compress the arrays and write them to a temporary file; the commit puts them in place.

        This is the expensive part of a save -- seconds for a large dataset -- and it needs no
        lock: the temporary name is unique to this process and call (``_tmp_path``), and nothing
        reads it. The commit, which :meth:`save_versioned` makes under the locks, writes the
        metadata to its own temporary file and renames both into place, the artifact first so
        there is never metadata without its artifact. Discarding removes the temporary file.
        """
        meta_path = self._meta_path(dataset_id)
        npz_path = self._npz_path(dataset_id)
        tmp_npz_path = self._tmp_path(npz_path)
        try:
            buffer = io.BytesIO()
            np.savez_compressed(buffer, **arrays)  # type: ignore[arg-type]  # numpy stubs incomplete for **kwargs
            tmp_npz_path.write_bytes(buffer.getvalue())
        except Exception:
            _discard_temp(tmp_npz_path, "NPZ")
            raise

        def commit(meta: DatasetMeta) -> None:
            tmp_meta_path = self._tmp_path(meta_path)
            meta_json = json.dumps(
                meta.model_dump(),
                default=_json_serializer,
                indent=JSON_INDENT_DEFAULT,
            )
            try:
                tmp_meta_path.write_text(meta_json, encoding=CHARSET_UTF8)
                # Atomically replace final files with the temporary ones.
                # Write NPZ first so we never have metadata without its NPZ.
                tmp_npz_path.replace(npz_path)
                tmp_meta_path.replace(meta_path)
            except Exception:
                _discard_temp(tmp_meta_path, "metadata")
                raise
            # Reached only when the writes above succeeded -- the ``except`` arm
            # re-raises. Without this the new dataset stays invisible to
            # ``filter_datasets`` / ``get_stats`` for the whole cache TTL, which is
            # read-your-writes broken.
            self._invalidate_metadata_cache()

        return StagedSave(commit, lambda: _discard_temp(tmp_npz_path, "NPZ"))

    def get_meta(self, dataset_id: str) -> DatasetMeta | None:
        """Get dataset metadata from filesystem.

        Args:
            dataset_id: Unique identifier for the dataset.

        Returns:
            Dataset metadata if found, None otherwise.
        """
        meta_path = self._meta_path(dataset_id)
        if not meta_path.exists():
            return None

        meta_json = meta_path.read_text(encoding=CHARSET_UTF8)
        meta_dict = json.loads(meta_json)

        return DatasetMeta(**meta_dict)

    def get_artifact_bytes(self, dataset_id: str) -> bytes | None:
        """Get dataset artifact as NPZ bytes.

        Args:
            dataset_id: Unique identifier for the dataset.

        Returns:
            NPZ file contents as bytes if found, None otherwise.
        """
        npz_path = self._npz_path(dataset_id)
        return npz_path.read_bytes() if npz_path.exists() else None

    def open_artifact_stream(self, dataset_id: str, chunk_size: int = ARTIFACT_STREAM_CHUNK_SIZE) -> Iterator[bytes] | None:
        """Read the NPZ off disk in chunks instead of materialising it whole.

        Defect-register ``APD-DATA-016``. The base-class default falls back to
        :meth:`get_artifact_bytes`, so peak memory there is still the full
        artifact; this backend has a file on disk and can do better, which is why
        it overrides.

        **Existence is decided eagerly, before the generator is returned.** A
        generator body does not run until first iteration, so testing for the file
        inside one would defer the ``None``/404 decision until after the caller had
        already committed to a 200 response — the route would have sent headers for
        a dataset that does not exist. The ``exists()`` check therefore stays out
        here, and only the reading is lazy.

        The handle is opened inside the generator and closed by its ``with`` block,
        so an abandoned download (client disconnects mid-stream) releases the file
        when the generator is finalised rather than holding it open.
        """
        npz_path = self._npz_path(dataset_id)
        if not npz_path.exists():
            return None

        def _chunks() -> Iterator[bytes]:
            with npz_path.open("rb") as handle:
                while True:
                    block = handle.read(chunk_size)
                    if not block:
                        return
                    yield block

        return _chunks()

    def exists(self, dataset_id: str) -> bool:
        """Check if dataset exists on filesystem.

        Args:
            dataset_id: Unique identifier for the dataset.

        Returns:
            True if both metadata and NPZ files exist, False otherwise.
        """
        return self._meta_path(dataset_id).exists() and self._npz_path(dataset_id).exists()

    def delete(self, dataset_id: str) -> bool:
        """Delete dataset from filesystem.

        Args:
            dataset_id: Unique identifier for the dataset.

        Returns:
            True if the dataset was deleted, False if it didn't exist.
        """
        # BUG-JD-02: idempotent unlink avoids the TOCTOU race in the prior
        # `if exists(): unlink()` pattern (another process could delete the
        # file between the check and the call). Return True if we actually
        # removed anything, False if both files were already gone.
        meta_path = self._meta_path(dataset_id)
        npz_path = self._npz_path(dataset_id)
        deleted = False
        for path in (meta_path, npz_path):
            try:
                path.unlink()
                deleted = True
            except FileNotFoundError:
                # Intentional no-op: a concurrent unlink (or simply a stray
                # missing sibling) is the exact race this idempotent loop is
                # designed to absorb. Treating absence as "nothing to do"
                # keeps ``delete`` safe to call repeatedly without surfacing
                # transient races to callers.
                continue
        if deleted:
            self._invalidate_metadata_cache()
        return deleted

    def list_datasets(self, limit: int = DEFAULT_LIST_LIMIT, offset: int = DEFAULT_LIST_OFFSET) -> list[str]:
        """List dataset IDs from filesystem.

        Finds datasets by globbing for .meta.json files.

        Args:
            limit: Maximum number of dataset IDs to return.
            offset: Number of dataset IDs to skip.

        Returns:
            List of dataset IDs.
        """
        meta_files = sorted(self._base_path.glob("*.meta.json"))
        dataset_ids = [f.stem.replace(".meta", "") for f in meta_files]
        return dataset_ids[offset : offset + limit]

    @property
    def base_path(self) -> Path:
        """Get the base storage path."""
        return self._base_path

    def update_meta(self, dataset_id: str, meta: DatasetMeta) -> bool:
        """Update dataset metadata on filesystem.

        Args:
            dataset_id: Unique identifier for the dataset.
            meta: Updated dataset metadata.

        Returns:
            True if the dataset was updated, False if it didn't exist.
        """
        # BUG-JD-03: Write to a sibling temp file and atomically replace the final
        # path so a crash mid-write cannot leave partial JSON readable to concurrent
        # readers. Matches the tmp+replace pattern already used by `save()`.
        meta_path = self._meta_path(dataset_id)
        if not meta_path.exists():
            return False

        meta_json = json.dumps(
            meta.model_dump(),
            default=_json_serializer,
            indent=JSON_INDENT_DEFAULT,
        )
        tmp_meta_path = self._tmp_path(meta_path)
        try:
            tmp_meta_path.write_text(meta_json, encoding=CHARSET_UTF8)
            tmp_meta_path.replace(meta_path)
        except BaseException:
            try:
                tmp_meta_path.unlink(missing_ok=True)
            except OSError:
                logging.debug(
                    "Failed to remove temporary metadata file %s during update_meta cleanup",
                    tmp_meta_path,
                    exc_info=True,
                )
            raise
        self._invalidate_metadata_cache()
        return True

    def list_all_metadata(self) -> list[DatasetMeta]:
        """List all dataset metadata from filesystem.

        Returns:
            List of all DatasetMeta objects.
        """
        # APD-DATA-012: sorted, because ``Path.glob`` specifies no ordering and does not
        # deliver one -- measured on ext4, its order is not sorted order. The total sort
        # in ``filter_datasets`` is what actually fixes tie order; this makes the
        # enumeration underneath it deterministic too, so any *other* consumer of this
        # method gets a reproducible sequence rather than directory-entry order.
        result = []
        for meta_file in sorted(self._base_path.glob("*.meta.json")):
            dataset_id = meta_file.stem.replace(".meta", "")
            meta = self.get_meta(dataset_id)
            if meta is not None:
                result.append(meta)
        return result
