"""Local filesystem dataset store."""

import contextlib
import fcntl
import io
import json
import logging
import os
import re
import uuid
from collections.abc import Iterator
from datetime import datetime
from pathlib import Path

# from typing import Any, Dict, List, Optional
from typing import Any

import numpy as np

from juniper_data.core.constants import CHARSET_UTF8
from juniper_data.core.models import DatasetMeta
from juniper_data.storage.base import DatasetStore
from juniper_data.storage.constants import (
    DEFAULT_LIST_LIMIT,
    DEFAULT_LIST_OFFSET,
    JSON_INDENT_DEFAULT,
    LOCK_FILE_SUFFIX,
    META_FILE_SUFFIX,
    NPZ_FILE_SUFFIX,
    TMP_FILE_SUFFIX,
)

# Dataset IDs are generated by ``generate_dataset_id`` as
# ``{generator}-{version}-{hash[:16]}`` where version strings may contain
# dots (e.g. ``spiral-v1.0.0-a3f8e12b4c567890``). The allowlist accepts
# alphanumerics, dot, underscore, and hyphen — explicitly excluding path
# separators, ``..`` parent references, and leading dots that could map to
# hidden files outside the storage directory (JD-SEC-01).
_VALID_DATASET_ID = re.compile(r"[A-Za-z0-9][A-Za-z0-9._\-]{0,127}")


def _validate_dataset_id(dataset_id: str) -> None:
    """Validate ``dataset_id`` against path traversal attacks.

    Raises:
        ValueError: If ``dataset_id`` is not a well-formed identifier. The
            caller is expected to translate this into an HTTP 400 at the
            request boundary.
    """
    if not isinstance(dataset_id, str) or not dataset_id:
        raise ValueError("dataset_id must be a non-empty string")
    if ".." in dataset_id:
        raise ValueError(f"Invalid dataset_id: {dataset_id!r}")
    if not _VALID_DATASET_ID.fullmatch(dataset_id):
        raise ValueError(f"Invalid dataset_id: {dataset_id!r}")


def _json_serializer(obj: Any) -> str:
    """JSON serializer for objects not serializable by default."""
    if isinstance(obj, datetime):
        return obj.isoformat()
    raise TypeError(f"Object of type {type(obj).__name__} is not JSON serializable")


class LocalFSDatasetStore(DatasetStore):
    """Local filesystem implementation of DatasetStore.

    Stores datasets as JSON metadata files and NPZ array files.

    Storage layout:
        {base_path}/{dataset_id}.meta.json
        {base_path}/{dataset_id}.npz
    """

    def __init__(self, base_path: Path) -> None:
        """Initialize the local filesystem store.
        Args:
            base_path: Base directory for storing datasets. Created if it doesn't exist.
        """
        self._base_path = Path(base_path)
        self._base_path.mkdir(parents=True, exist_ok=True)
        # Cache the resolved base so every lookup does not re-resolve symlinks.
        # The cached value is used as the reference point for the
        # defense-in-depth containment check in ``_build_path`` (JD-SEC-01).
        self._resolved_base = self._base_path.resolve()

    def _build_path(self, dataset_id: str, suffix: str) -> Path:
        """Construct a storage path for ``dataset_id`` with traversal defense.

        Applies two layers of protection (JD-SEC-01):

        1. ``_validate_dataset_id`` rejects identifiers containing parent
           references, path separators, or any character outside the
           permitted alphabet before the filesystem is touched.
        2. The constructed path is resolved and required to remain within
           ``self._resolved_base``, catching any traversal that slips past
           the regex via filesystem-level tricks (symlink abuse, etc.).
        """
        _validate_dataset_id(dataset_id)
        candidate = self._base_path / f"{dataset_id}{suffix}"
        resolved = candidate.resolve() if candidate.exists() else (self._resolved_base / candidate.name).resolve()
        if not resolved.is_relative_to(self._resolved_base):
            raise ValueError(f"Path traversal detected for dataset_id: {dataset_id!r}")
        return candidate

    def _meta_path(self, dataset_id: str) -> Path:
        """Get path to metadata file."""
        return self._build_path(dataset_id, META_FILE_SUFFIX)

    def _lock_path(self, dataset_id: str) -> Path:
        """Path of the advisory lock file guarding one dataset's metadata."""
        meta_path = self._meta_path(dataset_id)
        return meta_path.with_suffix(meta_path.suffix + LOCK_FILE_SUFFIX)

    @contextlib.contextmanager
    def _meta_write_lock(self, dataset_id: str) -> Iterator[None]:
        """Hold an exclusive advisory lock on this dataset's metadata (APD-DATA-007).

        The base class serialises the metadata read-modify-write only within one
        interpreter. Because this store's state is a shared directory, two *processes*
        against the same ``storage_path`` interleave freely, and the loser's whole
        document is overwritten. Reproduced before the fix: twelve processes each adding
        one distinct tag left two tags on disk.

        A separate lock file is used rather than locking the metadata file itself: the
        write path replaces that file by ``rename``, so a lock held on the old inode
        would guard nothing once the first writer swapped it out. The lock file is only
        ever created and locked, never renamed or removed -- unlinking it would let a
        second process create and lock a *different* inode by the same name and
        immediately enter the critical section.

        ``flock`` is advisory and per-host. It orders writers on one machine, including
        separate uvicorn workers, but is not a distributed lock and gives no guarantee
        over NFS.
        """
        lock_path = self._lock_path(dataset_id)
        lock_path.parent.mkdir(parents=True, exist_ok=True)
        # 0o600: the lock file carries no data -- it exists only as an flock target --
        # so nothing needs to read it and a world-readable mode is pure exposure
        # (CodeQL py/overly-permissive-file). Every process locking it runs as the
        # service user; cross-user locking would be a deliberate change, not a default.
        fd = os.open(lock_path, os.O_CREAT | os.O_RDWR, 0o600)
        try:
            fcntl.flock(fd, fcntl.LOCK_EX)
            try:
                yield
            finally:
                fcntl.flock(fd, fcntl.LOCK_UN)
        finally:
            os.close(fd)

    def _tmp_path(self, final_path: Path) -> Path:
        """A temp path unique to this process and call.

        BUG-JD-03 writes to a sibling temp file and ``replace()``s it over the final
        path so a crash cannot leave partial JSON readable. That temp name used to be
        derived from the final path alone, so two processes writing the same dataset
        chose the *same* temp file: one would replace it away while the other was still
        using it, and the loser raised ``FileNotFoundError`` mid-write. Found while
        reproducing APD-DATA-007. The pid+uuid suffix makes collision impossible; the
        atomic ``replace`` onto the final path is unchanged.
        """
        return final_path.with_suffix(f"{final_path.suffix}.{os.getpid()}.{uuid.uuid4().hex[:8]}{TMP_FILE_SUFFIX}")

    def _npz_path(self, dataset_id: str) -> Path:
        """Get path to NPZ file."""
        return self._build_path(dataset_id, NPZ_FILE_SUFFIX)

    def save(
        self,
        dataset_id: str,
        meta: DatasetMeta,
        arrays: dict[str, np.ndarray],
    ) -> None:
        """Save dataset metadata and arrays to filesystem.

        Args:
            dataset_id: Unique identifier for the dataset.
            meta: Dataset metadata.
            arrays: Dictionary of numpy arrays.

        Raises:
            IOError: If the save operation fails.
        """
        meta_path = self._meta_path(dataset_id)
        npz_path = self._npz_path(dataset_id)

        # Write to temporary files first, then atomically replace the final files
        tmp_meta_path = self._tmp_path(meta_path)
        tmp_npz_path = self._tmp_path(npz_path)

        meta_json = json.dumps(
            meta.model_dump(),
            default=_json_serializer,
            indent=JSON_INDENT_DEFAULT,
        )

        try:
            # Write metadata JSON to temporary file
            tmp_meta_path.write_text(meta_json, encoding=CHARSET_UTF8)

            # Write NPZ data to temporary file
            buffer = io.BytesIO()
            np.savez_compressed(buffer, **arrays)  # type: ignore[arg-type]  # numpy stubs incomplete for **kwargs
            buffer.seek(0)
            tmp_npz_path.write_bytes(buffer.read())

            # Atomically replace final files with the temporary ones.
            # Write NPZ first so we never have metadata without its NPZ.
            tmp_npz_path.replace(npz_path)
            tmp_meta_path.replace(meta_path)
        except Exception:
            # Best-effort cleanup of temporary files on failure
            try:
                tmp_meta_path.unlink(missing_ok=True)
            except OSError:
                logging.debug(
                    "Failed to remove temporary metadata file %s during cleanup",
                    tmp_meta_path,
                    exc_info=True,
                )
            try:
                tmp_npz_path.unlink(missing_ok=True)
            except OSError:
                logging.debug(
                    "Failed to remove temporary NPZ file %s during cleanup",
                    tmp_npz_path,
                    exc_info=True,
                )
            raise

    def get_meta(self, dataset_id: str) -> DatasetMeta | None:
        """Get dataset metadata from filesystem.

        Args:
            dataset_id: Unique identifier for the dataset.

        Returns:
            Dataset metadata if found, None otherwise.
        """
        meta_path = self._meta_path(dataset_id)
        if not meta_path.exists():
            return None

        meta_json = meta_path.read_text(encoding=CHARSET_UTF8)
        meta_dict = json.loads(meta_json)

        return DatasetMeta(**meta_dict)

    def get_artifact_bytes(self, dataset_id: str) -> bytes | None:
        """Get dataset artifact as NPZ bytes.

        Args:
            dataset_id: Unique identifier for the dataset.

        Returns:
            NPZ file contents as bytes if found, None otherwise.
        """
        npz_path = self._npz_path(dataset_id)
        return npz_path.read_bytes() if npz_path.exists() else None

    def exists(self, dataset_id: str) -> bool:
        """Check if dataset exists on filesystem.

        Args:
            dataset_id: Unique identifier for the dataset.

        Returns:
            True if both metadata and NPZ files exist, False otherwise.
        """
        return self._meta_path(dataset_id).exists() and self._npz_path(dataset_id).exists()

    def delete(self, dataset_id: str) -> bool:
        """Delete dataset from filesystem.

        Args:
            dataset_id: Unique identifier for the dataset.

        Returns:
            True if the dataset was deleted, False if it didn't exist.
        """
        # BUG-JD-02: idempotent unlink avoids the TOCTOU race in the prior
        # `if exists(): unlink()` pattern (another process could delete the
        # file between the check and the call). Return True if we actually
        # removed anything, False if both files were already gone.
        meta_path = self._meta_path(dataset_id)
        npz_path = self._npz_path(dataset_id)
        deleted = False
        for path in (meta_path, npz_path):
            try:
                path.unlink()
                deleted = True
            except FileNotFoundError:
                # Intentional no-op: a concurrent unlink (or simply a stray
                # missing sibling) is the exact race this idempotent loop is
                # designed to absorb. Treating absence as "nothing to do"
                # keeps ``delete`` safe to call repeatedly without surfacing
                # transient races to callers.
                continue
        return deleted

    def list_datasets(self, limit: int = DEFAULT_LIST_LIMIT, offset: int = DEFAULT_LIST_OFFSET) -> list[str]:
        """List dataset IDs from filesystem.

        Finds datasets by globbing for .meta.json files.

        Args:
            limit: Maximum number of dataset IDs to return.
            offset: Number of dataset IDs to skip.

        Returns:
            List of dataset IDs.
        """
        meta_files = sorted(self._base_path.glob("*.meta.json"))
        dataset_ids = [f.stem.replace(".meta", "") for f in meta_files]
        return dataset_ids[offset : offset + limit]

    @property
    def base_path(self) -> Path:
        """Get the base storage path."""
        return self._base_path

    def update_meta(self, dataset_id: str, meta: DatasetMeta) -> bool:
        """Update dataset metadata on filesystem.

        Args:
            dataset_id: Unique identifier for the dataset.
            meta: Updated dataset metadata.

        Returns:
            True if the dataset was updated, False if it didn't exist.
        """
        # BUG-JD-03: Write to a sibling temp file and atomically replace the final
        # path so a crash mid-write cannot leave partial JSON readable to concurrent
        # readers. Matches the tmp+replace pattern already used by `save()`.
        meta_path = self._meta_path(dataset_id)
        if not meta_path.exists():
            return False

        meta_json = json.dumps(
            meta.model_dump(),
            default=_json_serializer,
            indent=JSON_INDENT_DEFAULT,
        )
        tmp_meta_path = self._tmp_path(meta_path)
        try:
            tmp_meta_path.write_text(meta_json, encoding=CHARSET_UTF8)
            tmp_meta_path.replace(meta_path)
        except BaseException:
            try:
                tmp_meta_path.unlink(missing_ok=True)
            except OSError:
                logging.debug(
                    "Failed to remove temporary metadata file %s during update_meta cleanup",
                    tmp_meta_path,
                    exc_info=True,
                )
            raise
        return True

    def list_all_metadata(self) -> list[DatasetMeta]:
        """List all dataset metadata from filesystem.

        Returns:
            List of all DatasetMeta objects.
        """
        result = []
        for meta_file in self._base_path.glob("*.meta.json"):
            dataset_id = meta_file.stem.replace(".meta", "")
            meta = self.get_meta(dataset_id)
            if meta is not None:
                result.append(meta)
        return result
